### 1. Thử Đăng ký tài khoản mới
POST http://localhost:8081/api/auth/register
Content-Type: application/json

{
  "username": "huykha",
  "password": "123",
  "email": "kha@gmail.com"
}

### 2. Thử Đăng nhập
POST http://localhost:8081/api/auth/login
Content-Type: application/json

{
  "username": "huykha",
  "password": "123"
}