# SERVER
server.port=8081

# DATABASE
spring.datasource.url=jdbc:mysql://localhost:3306/coffee_shop?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=kha2004
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# THYMELEAF
spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8

# APP
spring.application.name=coffee-shop-backend